# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/hmpps-book-video-link
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: true
  host: book-video-link.prison.service.justice.gov.uk
  cert_secret: hmpps-book-video-link-cert
  path: /

env:
  API_ENDPOINT_URL: https://api.prison.service.justice.gov.uk/
  OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth/
  API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api.service.justice.gov.uk/
  API_PRISONER_OFFENDER_SEARCH_ENDPOINT_URL: https://prisoner-offender-search.prison.service.justice.gov.uk/
  HMPPS_COOKIE_NAME: hmpps-session-preprod
  REMOTE_AUTH_STRATEGY: "true"
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  VIDEO_LINK_ENABLED_FOR: "WWI,TSI,HEI"
  TOKENVERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true
  REDIS_ENABLED: true
  SUPPORT_URL: https://support.hmpps.service.justice.gov.uk/

whitelist:
  cloudplatform-live1-1: 35.178.209.113/32
  cloudplatform-live1-2: 3.8.51.207/32
  cloudplatform-live1-3: 35.177.252.54/32
  mojvpn: 81.134.202.29/32
  office: 217.33.148.210/32
  analyticplatform: 34.250.17.221/32
  analyticplatform: 34.251.212.33/32
  analyticplatform: 34.252.4.39/32
  ark-dom1-psn1: 51.247.4.0/24
  ark-dom1-psn2: 51.247.3.0/24
  ark-nps-hmcts-ttp1: 195.59.75.0/24
  ark-nps-hmcts-ttp2: 194.33.192.0/25
  ark-nps-hmcts-ttp3: 194.33.193.0/25
  ark-nps-hmcts-ttp4: 194.33.196.0/25
  ark-nps-hmcts-ttp5: 194.33.197.0/25
  dxc_webproxy1: 195.92.38.20/32
  dxc_webproxy2: 195.92.38.21/32
  dxc_webproxy3: 195.92.38.22/32
  dxc_webproxy4: 195.92.38.23/32
  moj-official-tgw-preprod: 51.149.251.0/24
  moj-official-tgw-prod: 51.149.250.0/24
  quantum1: 62.25.109.197/32
  quantum2: 212.137.36.230/32
  quantum3: 195.92.38.16/28
